#!/usr/bin/env python3
"""Generate the Johab symbol/hanja lookup table used by johab2unicode.

The Hangul syllable area of KS C 5601-1992 Johab is pure arithmetic and needs
no table (see docs/JOHAB_ENCODING.en.md §3).  The symbol and hanja area is not,
so it is emitted here as a dense 6016-entry table indexed by

    (leadIndex * 188) + trailIndex

Source of the mapping: CPython's built-in ``johab`` codec, whose tables come
from the Unicode Consortium's KS X 1001 mapping data.

Usage:  python3 tools/gen_johab_table.py           # rewrite both outputs
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

LEADS = list(range(0xD9, 0xDF)) + list(range(0xE0, 0xFA))
TRAILS = list(range(0x31, 0x7F)) + list(range(0x91, 0xFF))
SLOTS = len(LEADS) * 188


def build():
    out = [0] * SLOTS
    for li, lead in enumerate(LEADS):
        for trail in TRAILS:
            ti = trail - 0x31 if trail <= 0x7E else trail - 0x43
            try:
                ch = bytes([lead, trail]).decode("johab")
            except UnicodeDecodeError:
                continue
            assert len(ch) == 1 and ord(ch) <= 0xFFFF, (lead, trail, ch)
            out[li * 188 + ti] = ord(ch)
    return out


def as_source_chunks(table, width=48):
    """Escape the table as source-safe string chunks."""
    def esc(cp):
        if cp == 0:
            return "\\0"
        ch = chr(cp)
        if ch in ('"', "\\"):
            return "\\" + ch
        if cp < 0x20 or 0x7F <= cp <= 0xA0:
            return "\\u%04x" % cp
        return ch
    chunks = []
    for i in range(0, len(table), width):
        chunks.append("".join(esc(cp) for cp in table[i:i + width]))
    return chunks


HEADER = ("Generated by tools/gen_johab_table.py -- do not edit by hand.\n"
          "Johab symbol/hanja area: lead 0xD9-0xDE and 0xE0-0xF9, trail\n"
          "0x31-0x7E and 0x91-0xFE, flattened to (leadIndex * 188 + trailIndex).\n"
          "A code point of 0 means the slot is undefined.")


def write_js(table):
    chunks = as_source_chunks(table)
    body = "\n".join('  "%s" +' % c for c in chunks[:-1])
    body += '\n  "%s";' % chunks[-1]
    src = ("// " + HEADER.replace("\n", "\n// ") + "\n\n"
           "export const JOHAB_SYMBOL_TABLE =\n" + body + "\n")
    with open(os.path.join(ROOT, "src", "johab-symbols.js"), "w",
              encoding="utf-8") as fp:
        fp.write(src)


def write_py(table):
    chunks = as_source_chunks(table)
    body = "\n".join('    "%s"' % c for c in chunks)
    src = ('"""' + HEADER + '"""\n\n'
           "JOHAB_SYMBOL_TABLE = (\n" + body + "\n)\n")
    with open(os.path.join(ROOT, "tools", "johab_symbols.py"), "w",
              encoding="utf-8") as fp:
        fp.write(src)


if __name__ == "__main__":
    t = build()
    write_js(t)
    write_py(t)
    print("%d slots, %d defined" % (SLOTS, sum(1 for c in t if c)))
