#!/usr/bin/env python3
"""Generate the lookup table for Iyagi's user-defined glyph area.

Codes 0xD480-0xD4FF address the 128 glyphs of `ISPC.FNT`, the graphics font
that ships with Iyagi -- glyph number is the trail byte minus 0x80.  The
repertoire is IBM CP437's, five slots aside, so most of the mapping is
CP437's own Unicode correspondence; the rest was read off the font.

Source of the mapping: ``tools/iyagi_user_area.tsv``, which came from
disassembling the Iyagi For Windows installer and rendering the font.  Its
columns are the Johab code, the glyph number in `ISPC.FNT`, the CP437 byte
where there is one, the Unicode code point and character, how often the code
occurs in the 696-file ISS corpus, and a note.  The ``unicode`` column is what
is read here; ``char`` is there for people.

Usage:  python3 tools/gen_user_glyphs.py           # rewrite both outputs
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

FIRST = 0xD480
LAST = 0xD4FF
SLOTS = LAST - FIRST + 1


def build():
    out = [0] * SLOTS
    path = os.path.join(HERE, "iyagi_user_area.tsv")
    with open(path, encoding="utf-8") as fp:
        header = next(fp).rstrip("\n").split("\t")
        col = {name: i for i, name in enumerate(header)}
        for line in fp:
            if not line.strip():
                continue
            row = line.rstrip("\n").split("\t")
            code = int(row[col["johab"]], 16)
            assert FIRST <= code <= LAST, hex(code)
            value = row[col["unicode"]].strip()
            if not value:
                continue
            assert value.startswith("U+"), value
            out[code - FIRST] = int(value[2:], 16)
    return out


HEADER = ("Generated by tools/gen_user_glyphs.py -- do not edit by hand.\n"
          "Iyagi's user-defined glyph area: codes 0xD480-0xD4FF, indexed by\n"
          "(code - 0xD480).  Code points rather than a string, because two of\n"
          "them are astral.  A code point of 0 means the slot is undefined.")


def as_rows(table, width=8):
    for i in range(0, len(table), width):
        yield ", ".join("0x%04x" % cp for cp in table[i:i + width])


def write_js(table):
    body = "\n".join("  %s," % r for r in as_rows(table))
    src = ("// " + HEADER.replace("\n", "\n// ") + "\n\n"
           "export const USER_GLYPH_FIRST = 0x%04x;\n\n" % FIRST +
           "export const USER_GLYPH_TABLE = [\n" + body + "\n];\n")
    with open(os.path.join(ROOT, "src", "user-glyphs.js"), "w",
              encoding="utf-8") as fp:
        fp.write(src)


def write_py(table):
    body = "\n".join("    %s," % r for r in as_rows(table))
    src = ('"""' + HEADER + '"""\n\n'
           "USER_GLYPH_FIRST = 0x%04x\n\n" % FIRST +
           "USER_GLYPH_TABLE = (\n" + body + "\n)\n")
    with open(os.path.join(ROOT, "tools", "user_glyphs.py"), "w",
              encoding="utf-8") as fp:
        fp.write(src)


if __name__ == "__main__":
    t = build()
    write_js(t)
    write_py(t)
    print("%d slots, %d defined" % (SLOTS, sum(1 for c in t if c)))
